global:
  scrape_interval:     1s
  
  external_labels:
    monitor: 'demo'


scrape_configs:
  - job_name: 'demo'

    scrape_interval: 3s

    static_configs:
      - targets: ['localhost:8888']
      
remote_write:
  - url: http://localhost:9009/api/prom/push
